name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies 
      run: sudo apt-get update && sudo apt-get install libncurses5-dev libncursesw5-dev
    - name: reconf
      run: autoreconf -iv
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: make dist
      run: make dist
    - name: getfilename
      run: echo "::set-output name=file::$(ls csv-viewer-*.tar.gz)"
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: csv-viewer
        path: {{ steps.getfilename.outputs.file }}

